#!/bin/sh
#/home/al/preloader/prell
loadkmap</local/fr.bkmap
[ -e /dev/null ] || mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts none /dev/pts
[ -e /dev/shm ] || mkdir /dev/shm
mount -t tmpfs none /dev/shm
chmod 1777 /dev/shm
mount -t tmpfs none /run
mount -t proc none /proc
mount -t sysfs none /sys
#echo bfq > /sys/block/sda/queue/scheduler
mount -t efivarfs none /sys/firmware/efi/efivars
(e2fsck -v -y /dev/nvme0n1p2 2>&1) | tee /run/fsck.log
sysctl vm.dirty_writeback_centisecs=60000 vm.dirty_expire_centisecs=60000
#echo 1000 > /sys/block/sda/queue/iosched/read_expire
#echo 128 > /sys/block/sda/queue/iosched/fifo_batch
mount / -oremount,rw,noatime
#swapon /swap
rm -fr /tmp/.* /tmp/*
mkdir -m 1777 /tmp/.X11-unix /tmp/.ICE-unix
udevd -d
udevadm trigger --action=add
udevadm trigger --action=add -t subsystems
udevadm settle
hostname plop
ifconfig lo up
/usr/local/bin/launchix /usr/bin/xinit -- /opt/xlibre/bin/Xorg -nolisten tcp :0 vt5 -sharevts -novtswitch -keeptty &
ifconfig eth0 192.168.1.2 mtu 9194
route add default gw 192.168.1.1
cat > /etc/resolv.conf << EOF
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
EOF
dropbear -Rsw

